services:
  api:
    build: ./user-api
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/users"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    # Optional: The API is not required; comment this section to disable.

  tests:
    build: ./user-api-test
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://api:8080
